spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:test;MODE=MYSQL

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

    generate-ddl: true
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        #show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: ALWAYS


  server:
    servlet:
      multipart:
        maxFileSize: 20MB
        maxRequestSize: 50MB

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: koonsdiary-001.o3v9n6.0001.apn2.cache.amazonaws.com

  profiles:
    include:
      - jwt

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace